---
title: "Expression data analysis"
author: "Marie Locard-Paulet"
date: "14 December 2015"
output: html_document
---

I download the data from `GSE7460`: matrix.

```{r input, eval = F}
#source("https://bioconductor.org/biocLite.R")
#biocLite("GEOquery")
#biocLite(c("Biobase"))
library(GEOquery)
library(Biobase)
mygeomat <- getGEO("GSE7460", GSEMatrix=T)
save(list = ls(), file = "data.Rdata")
```

```{r}
load("data.Rdata")
show(mygeomat)
show(pData(phenoData(mygeomat[[1]]))[,c(1,6,8)])
names(pData(phenoData(mygeomat[[1]])))
mat <- pData(phenoData(mygeomat[[1]]))[,c(1,6,8)]
gsms <- rownames(mat[grepl("Treg", mat$title) | grepl("Tconv", mat$title),])
types <- as.character(mat$title[grepl("Treg", mat$title) | grepl("Tconv", mat$title)])
mat <- exprs(mygeomat[[1]])
```

The Affimetrix array uses the `moe430-20` Affymetrix Mouse Genome 430 2.0 Array (Annotation: GPL1261).

```{r conversion}
#biocLite("mouse4302.db")
library(mouse4302.db)
affyid <- rownames(mat)
egids2 <- mouse4302ENTREZID[affyid]
annots <- toTable(egids2)
```

I mapp `r length(unique(annots$probe_id))` on the `r length(unique(affyid))` IDs in input.

```{r}
str(annots)
mat1 <- mat[annots$probe_id,]
#if multiple probe sets map to a gene, select the one with maximal IQR 
iqrs=apply(mat1, 1, IQR)
sel.rn=tapply(1:nrow(annots), annots$gene_id, function(x){
 x[which.max(iqrs[x])]
 })
mat2=mat1[sel.rn,]
mapping <- data.frame("probes"=rownames(mat2), "GeneIDs"=names(sel.rn))
rownames(mat2)=names(sel.rn)
colnames(mat2) <- as.character(pData(phenoData(mygeomat[[1]]))[,c(1,6,8)]$title)

library(org.Mm.eg.db)
x <- org.Mm.egSYMBOL
# Get the gene symbol that are mapped to an entrez gene identifiers
mapped_genes <- mappedkeys(x)
# Convert to a list
xx <- as.list(x[mapped_genes])
if(length(xx) > 0) {
  # Get the SYMBOL for the first five genes
  xx[1:5]
  # Get the first one
  xx[[1]]
}
maptab <- cbind(names(xx), unlist(xx))
mat2 <- cbind(mat2, "GeneSymbol" = maptab[,2][match(rownames(mat2), maptab[,1])], "probes" = as.character(mapping$probes))
write.csv(mat2, "ExpressionDataReanalysed.csv")
```

```{r}
mat3 <- mat2[,grepl("Treg", colnames(mat2)) | grepl("Tconv", colnames(mat2))]
mat3 <- mat3[,!grepl("Act", colnames(mat3)) & !grepl("Thy", colnames(mat3))]
rownames(mat3) <- mat2[,(ncol(mat2)-1)]
head(mat3)

nmat <- matrix(ncol = 3, nrow = nrow(mat3))
nmat[,1] <- as.numeric(mat3[,1])/as.numeric(mat3[,2])
nmat[,2] <- as.numeric(mat3[,3])/as.numeric(mat3[,5])
nmat[,3] <- as.numeric(mat3[,4])/as.numeric(mat3[,6])
colnames(nmat) <- c("Expression Rep1", "Expression Rep2", "Expression Rep3")
rownames(nmat) <- rownames(mat3)
save(nmat, mat2, mat3, file = "ExpData.Rdata")
```

